name: Build Project

on:
  schedule:
    # Run at 00:00 UTC (midnight) every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENDOR_PNPM_ENABLED: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - name: Install dependencies
      run: pnpm install

    - name: Install Semgrep
      run: pip install semgrep==1.99.0

    - name: Build
      run: pnpm run build

    - name: Endor Labs SCA Scan
      uses: endorlabs/github-action@v1.1.8
      with:
        namespace: "arsalan-learn"
        enable_github_action_token: true
        scan_dependencies: true
        pr: false
        additional_args: "--as-default-branch --ai-models"