name: Build Project

on:
  schedule:
    # Run at 00:00 UTC (midnight) every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check for TypeScript errors
      run: npx tsc --noEmit

    - name: Build
      run: npm run build 